### ISSUE TITLE
use k8s job to install drbd instead of daemonset?

### ISSUE THREAD

**Issue by panpan0000** [hwameistor/drbd-adapter#17]
job may be more suitable for init works which run once

**Comment by alexzhc** [comment]
`DaemonSet` by default spawns a single pod on each node. That's why it is used in the first place. 

`Job` on the other hand needs to set `nodeAffinity` with each node name for each `job`, which requires obtaining `kubectl get no` when the chart is applied. 

The latter is doable now with helm `lookup` function.
